### ISSUE TITLE
纳妃对象包括直系亲属

### ISSUE THREAD

**Issue by jiangsheng** [luiges90/ZHSan#104]
新年更新的版本，280年英雄集结剧本开始种田。结果种到一半翻武将数据看到栾提去卑和栾提氏生了个孩子，被栾提于夫罗为妃子了，但是问题是栾提于夫罗在游戏里是栾提氏的老爹，虽说是外族，有这么纳妃的么……

**Comment by luiges90** [comment]
劇本裡好像沒有正確設置親屬闗係
