### ISSUE TITLE
我切到v1.1分支，生成项目一直报错说找不到资源文件，请问下该怎么构建呢，我想先构建个pc版

### ISSUE THREAD

**Issue by hzl2928963** [luiges90/ZHSan#50]
![image](https://user-images.githubusercontent.com/3132162/34646974-b3b43ec6-f3b0-11e7-988e-44a8cfe4b833.png)
请问下这个问题怎么解决？我还没改过什么文件，第一次构建就失败了
希望能给个比较完整的配置教程

**Comment by luiges90** [comment]
剛剛更新了gitignore，上傳了字庫，試一試?

**Comment by hzl2928963** [comment]
MonoGame 好像有问题 但我不知道为什么路径错了

**Comment by luiges90** [comment]
什麼問題?

**Comment by hzl2928963** [comment]
搞定了，这些路径配置在WorldOfTheThreeKingdoms.csproj文件里，下面这样的条目有500多条
<Content Include="..\Content\Sound\Animation\Female\57.xnb">
      <Link>Content\bin\Win\Sound\Animation\Female\57.xnb</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
我把路径中的“bin\Win“都去掉了，就编译通过了
