### ISSUE TITLE
请问下UI界面是用什么工具做的？

### ISSUE THREAD

**Issue by hzl2928963** [luiges90/ZHSan#51]
目前看了源码发现UI界面都是从xml文件加载的，请问下这些xml文件是用什么工具制作出来的？

**Comment by luiges90** [comment]
xml沒有特別工具，用記事本也可以 😊 
當然好一些的例如Notepad++

**Comment by hzl2928963** [comment]
哇，纯手动敲出来的界面吗？比如我想开发个新的界面，怎么破，有没有什么UI 编辑器啥的可以用捏？

**Comment by luiges90** [comment]
GamePlugins 裡的代面就是有關各個界面的，的確是用手敲 😅
